apiVersion: apps/v1
kind: Deployment
metadata:
  name: rru
  namespace: ion
spec:
  selector:
    matchLabels:
      app: rru
  template:
    metadata:
      labels:
        app: rru
      annotations:
        "cni.projectcalico.org/ipAddrs": "[\"192.168.0.112\"]"
    spec:
      containers:
      - name: rru
        image: seyed2
        securityContext:
          privileged: true
        imagePullPolicy: IfNotPresent
        env:
          - name: USE_VOLUMED_CONF
            value: "1"
          # - name: USE_B2XX
          #   value: "1"
          - name: UHD_IMAGES_DIR
            value: "/usr/local/share"
        volumeMounts:
          - mountPath: /dev/bus/usb
            name: usbbus
          - mountPath: /opt/oai-enb/etc/mounted.conf
            name: rruconf
            subPath: mounted.conf
          - mountPath: /usr/local/share
            name: uhdimg
        ports:
        - containerPort: 50000
        - containerPort: 50001
      initContainers:
        - name: mmechecker
          image: subfuzion/netcat
          imagePullPolicy: Never
          command: ['sh', '-c', "for i in {1..100}; do sleep 10; if nc -z 192.168.0.130 3870; then exit 0; fi; done; exit 1"]
      volumes:
        - name: usbbus
          hostPath:
            path: /dev/bus/usb
        - name: rruconf
          configMap:
            name: rrucfg
        - name: uhdimg
          hostPath:
            path: /home/ion/uhd
      nodeSelector:
        environment: rru
